// <auto-generated />
using System;
using AIDocumentMeetingAssistant.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIDocumentMeetingAssistant.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723235244_RefactorAisummariesAndQuestionsRelations")]
    partial class RefactorAisummariesAndQuestionsRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Aisummary", b =>
                {
                    b.Property<Guid>("Aisummary_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Aisummary_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Meeting_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Aisummary_Id");

                    b.HasIndex("Meeting_Id");

                    b.ToTable("Aisummaries");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Answer", b =>
                {
                    b.Property<Guid>("Answer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Question_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Answer_Id");

                    b.HasIndex("Question_Id")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Document", b =>
                {
                    b.Property<Guid>("Document_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Document_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document_FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document_FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document_FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("Meeting_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Document_Id");

                    b.HasIndex("Meeting_Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Meeting", b =>
                {
                    b.Property<Guid>("Meeting_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Meeting_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Participants")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Meeting_Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.MeetingNote", b =>
                {
                    b.Property<Guid>("MeetingNote_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Meeting_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NotesContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetingNote_Id");

                    b.HasIndex("Meeting_Id");

                    b.ToTable("MeetingNotes");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Question", b =>
                {
                    b.Property<Guid>("Question_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Meeting_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Question_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Question_Id");

                    b.HasIndex("Meeting_Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Role", b =>
                {
                    b.Property<Guid>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.User", b =>
                {
                    b.Property<Guid>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Aisummary", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.Meeting", "Meeting")
                        .WithMany("Aisummaries")
                        .HasForeignKey("Meeting_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Answer", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("AIDocumentMeetingAssistant.API.Models.Answer", "Question_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Document", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.Meeting", "Meeting")
                        .WithMany("Documents")
                        .HasForeignKey("Meeting_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Meeting", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.User", "CreatedBy")
                        .WithMany("Meetings")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.MeetingNote", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.Meeting", "Meeting")
                        .WithMany("MeetingNotes")
                        .HasForeignKey("Meeting_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Question", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.Meeting", "Meeting")
                        .WithMany("Questions")
                        .HasForeignKey("Meeting_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.User", b =>
                {
                    b.HasOne("AIDocumentMeetingAssistant.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Meeting", b =>
                {
                    b.Navigation("Aisummaries");

                    b.Navigation("Documents");

                    b.Navigation("MeetingNotes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Question", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AIDocumentMeetingAssistant.API.Models.User", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
